### ISSUE TITLE
A busca cega que "implementamos" não parece adequado 

### ISSUE THREAD

**Issue by abbudao** [kollinslima/trabalho1_IA#1]
Galera,
Tava aqui estudando o código, e parece que nossa busca não é bem o que a gente definiu no problema. A busca no caso, definido um nó inicial e um nó final, retorna os nós transcorridos entre eles. No caso, todos os nossos nós são conectados com todos os outros, garantindo que a resposta seja sempre `[Nó_inicial, Nó_final].` 
Outro problema é que no problema do caxeiro viajante temos que passar por todos os nós de interesse, algo que não foi modelado no problema.
Estou pesquisando mais a respeito,
Quem puder dar um input, é sempre bem-vindo.

**Comment by gustavojoseleite** [comment]
sim, esta errado.Estou na monitoria vendo isso.

Em 26/04/2017 15:17, "abbudao" <notifications@github.com> escreveu:

**Comment by gustavojoseleite** [comment]
Pessoal,
Conversei com a monitora a respeito do trabalho e ela esclareceu alguns pontos.
O código que consta no git é apenas a implementação da busca cega. Pensei em realizar alterações nele de acordo com o nosso problema, mas não consegui muita evolução, discuti algumas soluções com a monitora mas nada concreto, vou continuar tentando seguindo o que discutimos.
Ainda sobre a busca cega, cheguei a conversar com ela também a respeito de todos os nós serem conectados e se o algoritmo que pretendemos utilizar não falharia em alguns casos. Ela disse que provavelmente não haverá problema e que podemos utilizar o código como está no slide apenas realizando modificações para obter o menor custo.
Bom é isso, ela ficou a disposição para ajudar no que for preciso. E qualquer coisa que eu conseguir vou passando para vocês.
